### PR TITLE
Rfmon support rebased

### PR DESCRIPTION
**Pull request by hellais**
This is a rebase of this branch: https://github.com/pynetwork/pypcap/pull/32

cc @gpotter2

### CODE REVIEW

**Comment by gpotter2** [comment]
Thanks ! I will investigate so see if this works

**Comment by gpotter2** [comment]
Merge ?

**Comment by hellais** [comment]
I actually haven't had a chance to test this extensively, but if @gpotter2 you say it's working well for you I can proceed with merging it.

**Comment by gpotter2** [comment]
To be fair, I couldn't test it either... I don't currently have access to a computer supporting this :/ Will see If someone can do it for me

**Comment by gpotter2** [comment]
One user reported that it's working !
https://github.com/secdev/scapy/pull/1350#issuecomment-383711164
Should be mergeable

**Comment by ograff** [comment]
If more directed testing is needed I'll have time after Thursday

**Comment by hellais** [comment]
@gpotter2 thanks for the input on this. I am going to merge this into master. Do some smoke testing to ensure nothing breaks for the current use cases and then cut a new release.

**Comment by hellais** [comment]
@gpotter2 I just cut 1.2.1 and uploaded it to pypi. Enjoy!

**Comment by gpotter2** [comment]
Thanks !!

**Pull request merged**
