### PR TITLE
Regenerate C code (Fix setup issue on Python 3.7)

### PR DESCRIPTION
**Pull request by lambdalisue**
To support building pypcap in Python 3.7, the latest cython was required.

Related issues
https://github.com/numpy/numpy/issues/10500
https://github.com/cython/cython/issues/1955

### CODE REVIEW

**Comment by hellais** [comment]
@lambdalisue thanks for working on this.

To confirm is it the case that I can just update to the latest cython and push the rebuilt pcap.c? What is the required cython version?

We should probably codify this somewhere in the https://github.com/pynetwork/pypcap/blob/master/Makefile#L20 to ensure we are always using a version that will not break python 3.7 support.

**Comment by lambdalisue** [comment]
@hellais Sorry for the really late reply. I forgot about this PR.

> To confirm is it the case that I can just update to the latest cython and push the rebuilt pcap.c? What is the required cython version?

Yes. And this time, it's 0.29.7, which is written in the header of [pypcap.h](https://github.com/pynetwork/pypcap/blob/025deff92a40394044605c82d6d02a4ac2e93ccc/pcap.c#L1)

> We should probably codify this somewhere in the https://github.com/pynetwork/pypcap/blob/master/Makefile#L20 to ensure we are always using a version that will not break python 3.7 support.

Instead, I added `py37` to the tox.

**Comment by lambdalisue** [comment]
I'll remove the title `- WIP` once the Travis works correctly... 😢

**Comment by lambdalisue** [comment]
Finally :tada:

**Comment by hellais** [comment]
Sorry for getting back to you so late. This looks good to me. I am merging.

**Comment by lambdalisue** [comment]
So could you please upload the next version to PyPI?

**Comment by hellais** [comment]
> So could you please upload the next version to PyPI?

Yes I am going to look into doing this today.

**Comment by hellais** [comment]
Tagged and uploaded a new release: https://pypi.org/project/pypcap/1.2.3/.

Let me know how it goes.

**Pull request merged**
