### PR TITLE
just a tiny bit of setup.py cleanup also test push to pypitest

### PR DESCRIPTION
**Pull request by brifordwylie**
Test the distribution by running the following:

    pip install -i https://testpypi.python.org/pypi pypcap

If we feel like is okay, we'll push to the official pypi, this will include the Mac fix #8 and Issue request #9

### CODE REVIEW

**Comment by brifordwylie** [comment]
Okay, going to go ahead and merge this as it's been sitting here for  over a month :)

**Comment by hellais** [comment]
You did the right thing. Apologies for not tending to it sooner. Next time I am so irresponsive ping me another time to do the review, that I may have been in a super busy period and the notification was lost in the void.

**Comment by hellais** [comment]
Also I noticed you changed the version number. We should hence probably do a new release?

Shall I do it or do you have all you need to do it?

**Comment by brifordwylie** [comment]
Hi @hellais, okay next time I'll ping you before merging anything. 

Here's the release 'process' (too strong of a word :) that I put together for dpkt. We can follow that or do something else if you like. In general I'm not a fan of 'github releases' (see bottom paragraph), but this is your ship so happy to do whatever you want.

https://dpkt.readthedocs.org/en/latest/admin_notes.html#pypi-release-how-to

**Pull request merged**
